import placeHolder from '../../assets/Imgs/LogoFG.jpg'

const AllProducts = [
  {
    id: '0',
    category: 'Categoria1',
    name: 'Produto1',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '1',
    category: 'Categoria2',
    name: 'Produto2',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '2',
    category: 'Categoria3',
    name: 'Produto3',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '3',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '4',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '5',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '6',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '7',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '8',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '9',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '10',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '11',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '12',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '13',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '14',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '15',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '16',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '17',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '18',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '19',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
]

export default AllProducts
