import placeHolder from '../../assets/Imgs/LogoFG.jpg'

const AllProducts = [
  {
    id: '0',
    category: 'Categoria1',
    name: 'Produto1',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '1',
    category: 'Categoria2',
    name: 'Produto2',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '2',
    category: 'Categoria3',
    name: 'Produto3',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '3',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '3',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '3',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '3',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '3',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '3',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '3',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '3',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '3',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '3',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '3',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '3',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '3',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '3',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '3',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '3',
    category: 'Categoria4',
    name: 'Produto4',
    img: placeHolder,
    price: 100,
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
]

export default AllProducts
