import placeHolder from '../../assets/Imgs/LogoFG.jpg'

const AllProducts = [
  {
    id: '0',
    category: 'Substratos para aquários',
    name: 'Produto1',
    img: placeHolder,
    price: 'R$ 100,00',
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '1',
    category: 'Condicionadores de água',
    name: 'Produto2',
    img: placeHolder,
    price: 'R$ 100,00',
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '2',
    category: 'Bonsais e Terrários',
    name: 'Produto3',
    img: placeHolder,
    price: 'R$ 100,00',
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '3',
    category: 'Areia para gaiola',
    name: 'Produto4',
    img: placeHolder,
    price: 'R$ 100,00',
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '4',
    category: 'Areia para gaiola',
    name: 'Produto4',
    img: placeHolder,
    price: 'R$ 100,00',
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '5',
    category: 'Areia para gaiola',
    name: 'Produto4',
    img: placeHolder,
    price: 'R$ 100,00',
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '6',
    category: 'Areia para gaiola',
    name: 'Produto4',
    img: placeHolder,
    price: 'R$ 100,00',
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '7',
    category: 'Areia para gaiola',
    name: 'Produto4',
    img: placeHolder,
    price: 'R$ 100,00',
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '8',
    category: 'Areia para gaiola',
    name: 'Produto4',
    img: placeHolder,
    price: 'R$ 100,00',
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '9',
    category: 'Areia para gaiola',
    name: 'Produto4',
    img: placeHolder,
    price: 'R$ 100,00',
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '10',
    category: 'Areia para gaiola',
    name: 'Produto4',
    img: placeHolder,
    price: 'R$ 100,00',
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '11',
    category: 'Areia para gaiola',
    name: 'Produto4',
    img: placeHolder,
    price: 'R$ 100,00',
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '12',
    category: 'Areia para gaiola',
    name: 'Produto4',
    img: placeHolder,
    price: 'R$ 100,00',
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '13',
    category: 'Areia para gaiola',
    name: 'Produto4',
    img: placeHolder,
    price: 'R$ 100,00',
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '14',
    category: 'Areia para gaiola',
    name: 'Produto4',
    img: placeHolder,
    price: 'R$ 100,00',
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '15',
    category: 'Areia para gaiola',
    name: 'Produto4',
    img: placeHolder,
    price: 'R$ 100,00',
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '16',
    category: 'Areia para gaiola',
    name: 'Produto4',
    img: placeHolder,
    price: 'R$ 100,00',
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '17',
    category: 'Areia para gaiola',
    name: 'Produto4',
    img: placeHolder,
    price: 'R$ 100,00',
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '18',
    category: 'Areia para gaiola',
    name: 'Produto4',
    img: placeHolder,
    price: 'R$ 100,00',
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },
  {
    id: '19',
    category: 'Areia para gaiola',
    name: 'Produto4',
    img: placeHolder,
    price: 'R$ 100,00',
    description: 'Descição do Produto1 completa',
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  },

  ...Array.from({ length: 100 }, (_, i) => ({
    id: (20 + i).toString(),
    category: 'Areia para gaiola',
    name: `Produto${20 + i}`,
    img: placeHolder,
    price: 'R$ 100,00',
    description: `Descrição do Produto${20 + i} completa`,
    button: {
      label: 'Comprar',
      link: 'https://www.google.com',
    },
  })),
]

export default AllProducts
